# Generated by Django 4.1.6 on 2023-02-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='flavour',
        ),
    ]
