# Generated by Django 4.1.7 on 2023-03-16 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='placed_at',
            new_name='created_at',
        ),
    ]
